---

# Make sure to insert secure passwords!!


db_password: i4@Lc3KWLnJg
admin_password: evfIET4&05Uj


# Secret Token
# This is required to verify session. It must be at least 30 characters and
# random. This must be changed for a production server.
# Generate one with a bash command like: openssl rand -hex 128
secret_token: '6687291ab74f1d65703523722b4c471944ef3c4dfd410c27709cdf0a51b1b7598ac00da298b4e6084a0ac954a381222cc0185d0cc8abac45090f12c6cadabda60257b71d16b4eba39ef2a7bb721da1c8518d982058de3c1b9bd638addc6110dd437431a29c4862b8da14200b1803899e9e95486f921f2a4b4e2dc6af641ccf3a'

# Create a Google Maps API key and enable Javascript and Places libraries
google_maps_api_key: AIzaSyAHODzT_bP5lSzA1KBlK_VRCAc9OxHpLoI

# Set these if using Amazon S3
#s3_access_key:
#s3_secret:
#s3_region:
#s3_images_bucket:
#s3_backups_bucket:

# Stripe Connect API keys
# Find these under 'API keys' and 'Connect' in your Stripe account dashboard -> Account Settings
# Under 'Connect', the Redirect URI should be set to https://YOUR_SERVER_URL/stripe/callbacks (e.g. https://openfoodnetwork.org.uk/stripe/callbacks)
# Under 'Webhooks', you should set up a Connect endpoint pointing to https://YOUR_SERVER_URL/stripe/webhooks e.g. (https://openfoodnetwork.org.uk/stripe/webhooks)
# Different keys can be made for testing or live environments
stripe_client_id: ca_FmW8K8WNLrRh30cmLnd01lZ0A3mwNlP8
stripe_instance_secret_key: sk_test_kCZ2JkFuBuX4Ac3CkiOOoBOa0074FFDsDu
stripe_instance_publishable_key: pk_test_acN51nlyfSZQRdeHccWoO6nP00lVY6g3c6
stripe_endpoint_secret: whsec_fSTl4hr9x9Sqop4HiFleXVA0enUrBSlm

# Skylight's API key. This enables performance instrumentation through Skylight. See https://github.com/openfoodfoundation/openfoodnetwork/pull/2070 for details.
#skylight_authentication: ""

# Mail settings
mail_host: smtp.sendgrid.net
mail_port: '587'
smtp_username: apikey
smtp_password: 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

# Optional mail settings
## Connection type 'TLS' means STARTTLS usually on port 587
## Connection type 'SSL' means SSL/TLS usually on port 465
mail_secure_connection: 'TLS'
mails_from: noreply@openfoodnetwork.org.nz
# mail_bcc: bcc_me@example.com

# Datadog monitoring. See
# https://github.com/openfoodfoundation/ofn-install/issues/287 for details.
# Note we have a single OFN account where all servers send their metrics to.
#
# datadog_key: 'API_key_for_the_OFN_account'

# Bugsnag collects all errors and notifies you.
# https://github.com/openfoodfoundation/ofn-install/wiki/Issue-reporting
#
#bugsnag_key: ''


# Example settings for integrations like Zapier.
# ----------------------------------------------
# Generate a strong password with this command: `openssl rand -hex 128`.
#
# You can add one or multiple entries using the lists (with dashes), then run
# the `db_integrations.yml` playbook on the target server. Then, provision the
# server for the changes on the datadog agent to take place.
#
# To disable an integration, change the `state` key from `present` to: `absent`,
# remove the custom_* entries, then run the db_integrations.yml playbook again.

#db_integrations:
#  - { user: zapier, state: present, password: incredibly_strong_password_goes_here }


# For Datadog you will need the following:
#
#datadog_db_password: secure_password_goes_here
#
#db_integrations:
#  - { user: datadog, state: present, password: "{{ datadog_db_password }}" }
