---

# Make sure to insert secure passwords!!


db_password: Hello123$

admin_password: Hello123$


# Secret Token
# This is required to verify session. It must be at least 30 characters and
# random. This must be changed for a production server.
# Generate one with a bash command like: openssl rand -hex 128
secret_token: 2f7386f34d078416fa46c48b9008999c3641073861a909993d1c77c8dcd6f391507a712248a1b06d61d1b0302d483362f6816fc9bd6edf9172c0f203a486dbf35b26789384a4240dca602aa5166f324807bc2337cb465fc669371a6eaa9e890929f115985d05133eb4989dacf619f0b52aeb83d3d695a1a9296da01a2e19e7ed

# Create a Google Maps API key and enable Javascript and Places libraries
google_maps_api_key: AIzaSyBt0Qto8mG7LhCT6hW6EZbeQ0n4lAblpvA

# Set these if using Amazon S3
#s3_access_key:
#s3_secret:
#s3_region:
#s3_images_bucket:
#s3_backups_bucket:

# Stripe Connect API keys
# Find these under 'API keys' and 'Connect' in your Stripe account dashboard -> Account Settings
# Under 'Connect', the Redirect URI should be set to https://YOUR_SERVER_URL/stripe/callbacks (e.g. https://openfoodnetwork.org.uk/stripe/callbacks)
# Under 'Webhooks', you should set up a Connect endpoint pointing to https://YOUR_SERVER_URL/stripe/webhooks e.g. (https://openfoodnetwork.org.uk/stripe/webhooks)
# Different keys can be made for testing or live environments
stripe_client_id: ca_FbbSmnqgWSPGL309JywFxxGXgllqDwKE
stripe_instance_secret_key: sk_test_xdixKB0UCFuDlDwQ2fT9c86K00M3x4v0tx
stripe_instance_publishable_key: pk_test_eypiy98tPrLoz2qRYD18MXkA00Fo6Al2ts
stripe_endpoint_secret: whsec_8tcrbdb6Rnq48MridnULLTFftGpesEs2

# Skylight's API key. This enables performance instrumentation through Skylight. See https://github.com/openfoodfoundation/openfoodnetwork/pull/2070 for details.
#skylight_authentication: ""

# Mail settings
mail_host: smtp.sendgrid.net
mail_port: '25'
smtp_username: apikey
smtp_password: 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

# Optional mail settings
## Connection type 'TLS' means STARTTLS usually on port 587
## Connection type 'SSL' means SSL/TLS usually on port 465
# mail_secure_connection: 'TLS'
# mails_from: from_address@example.com
# mail_bcc: bcc_me@example.com

# Datadog monitoring. See
# https://github.com/openfoodfoundation/ofn-install/issues/287 for details.
# Note we have a single OFN account where all servers send their metrics to.
#
# datadog_key: 'API_key_for_the_OFN_account'

# Bugsnag collects all errors and notifies you.
# https://github.com/openfoodfoundation/ofn-install/wiki/Issue-reporting
#
#bugsnag_key: ''


# Example settings for integrations like Zapier.
# ----------------------------------------------
# Generate a strong password with this command: `openssl rand -hex 128`.
#
# You can add one or multiple entries using the lists (with dashes), then run
# the `db_integrations.yml` playbook on the target server. Then, provision the
# server for the changes on the datadog agent to take place.
#
# To disable an integration, change the `state` key from `present` to: `absent`,
# remove the custom_* entries, then run the db_integrations.yml playbook again.

#db_integrations:
#  - { user: zapier, state: present, password: incredibly_strong_password_goes_here }


# For Datadog you will need the following:
#
#datadog_db_password: secure_password_goes_here
#
#db_integrations:
#  - { user: datadog, state: present, password: "{{ datadog_db_password }}" }
